= Java8 => 람다 표현식

=== 람다 표현식 나오기 전 정렬 예제

[source, java]
----
public class Main {
    public static void main(String[] args) {
        List<Integer> numbers = Arrays.asList(4, 2, 3, 1);

        numbers.sort(new Comparator<Integer>() {
            @Override
            public int compare(Integer o1, Integer o2) {
                return o1 > o2 ? 1 : -1;
            }
        });

        System.out.println(numbers);
    }

}
----

=== 람다 표현식

===== 람다
* 메서드로 전달할 수 있는 익명함수를 단순화한 것
* 특성
** 익명 => 이름 없는 메서드
** 함수 => 특정 클래스에 종속적이지 않음. 메서드처럼 파라미터 리스트, 바디, 반환형식, 가능한 예외리스트를 포함
** 전달 => 람다 표현식을 메서드 인수로 전달하거나 변수로 저장함
** 간결성
* 형태

[source, java]
----
() -> {}    // 파라미터와 반환값 둘다 없음
() -> 42    // 파라미터가 없으며, 42를 반환함
() -> null  // 파라미터가 없으며, null이 반환됨
() -> { return 42; }    // 괄호와 함께 사용시 "return"과 ";"는 생략 불가능
() -> { System.gc(); }  // 반환값이 없음. 내부 문장만 실행됨
() -> {
  if (true) return 12;
  else {
    int result = 15;
    for (int i = 1; i < 10; i++)
      result *= i;
    return result;
  }
}                    // 한번에 여러 라인을 람다의 바디에 기술 가능
(int x) -> x+1       // 파라미터는 아래와 같이 작성할 수 있음
(int x) -> { return x+1; }  //위의 문장과 동일함
(x) -> x+1           // 파라미터의 타입은 생략가능함
x -> x+1             // 파라미터가 있는 경우 파라미터의 괄호는 생략가능함
(String s) -> s.length()
(Thread t) -> { t.start(); }
s -> s.length()
t -> { t.start(); }
(int x, int y) -> x+y
(x,y) -> x+y
----

===== 람다를 사용할 수 있는 조건
* `default` 메서드가 여러 개 존재하더라도 추상 메서드가 하나라면 함수형 인터페이스(= 하나의 추상 메서드를 가진 인터페이스)임
** `default` 메서드는 인터페이스에서 메서드에서 메서드 구현부를 작성할 수 있음
* `@FunctionalInterface` 어노테이션이 존재함
** Java가 함수형 프로그래밍을 쓰기 위해 정의해놓은 어노테이션
* 어노테이션이 선언된 인터페이스에서 메서드를 호출할 때 인자를 제대로 넘기지 않으면 컴파일 오류가 남
* Java8 하위 호환성 때문에 생김

[source, java]
----
@FunctionalInterface
public interface Comparator<T> {
    // ...

    default <U extends Comparable<? super U>> Comparator<T> thenComparing( Function<? super T, ? extends U> keyExtractor) {
        return thenComparing(comparing(keyExtractor));
    } 

    // ...
}
----

[source, java]
----
public class Main {
    public static void main(String[] args) {
        List<Integer> numbers = Arrays.asList(4, 2, 3, 1);

        // 람다 표현식
        numbers.sort((o1, o2) -> o1 > o2 ? 1 : -1);

        // 메서드 레퍼런스
        numbers.sort(Integer::compareTo);

        System.out.println(numbers);
    }

}
----

[source, java]
----
public class Main {

    public static void main(String[] args) {
        List<Integer> numbers = Arrays.asList(4, 2, 3, 1);

        // 자바에서 제공하는 함수형 인터페이스
        List<Integer> collect = numbers.stream().map(new Function<Integer, Integer>() {
            @Override
            public Integer apply(Integer a) {
                return a * 2;
            }
        }).collect(Collectors.toList());

        List<Integer> collect2 = numbers.stream().map(a -> a * 2).collect(Collectors.toList());

        System.out.println(collect);
        System.out.println(collect2);
    }

}
----

=== 자바에서 제공하는 함수형 인터페이스
* https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html[Java8 Documents]

===== Predicate
* `(T) -> boolean`
** 제네릭 형식의 T 객체를 인수로 받아 boolean을 반환함
** T 형식의 객체가 조건식이 맞는지 검사함

[source,java]
----
Predicate<Apple> predicate1 = new Predicate<Apple>() {
     @Override
     public boolean test(Apple apple) {
         return apple.getColor().equals("green");
     }
  };
Predicate<Apple> predicate2 = apple -> apple.getColor().equals("green");
----

===== Consumer
* `(T) -> void`
** 제네릭 형식의 T 객체를 받아서 void를 반환함
** T 형식의 객체를 인수로 받아서 어떤 동작을 수행할 때 사용함

[source,java]
----
Consumer<Apple> consumer1 = new Consumer<Apple>() {
    @Override
    public void accept(Apple apple) {
        System.out.println(apple);
    }
};

Consumer<Apple> consumer2 = System.out::println;
----

===== Function
* `(T)->R`
** 제네릭 형식의 T를 인수로 받아서 제네릭 형식의 R 객체를 반환함

[source,java]
----
Function<Apple, Integer> function1 = new Function<Apple, Integer>() {
    @Override
    public Integer apply(Apple apple) {
        return apple.getWeight();
    }
};

Function<Apple, Integer> function2 = Apple::getWeight;
----

=== 메서드 레퍼런스
* 메서드 레퍼런스
** 특정 메스드만을 호출하는 람다의 축약형이라고 생각할 수 있다. 메서드명 앞에 구분자(::)를 붙이는 방식으로 메서드 레퍼런스를 활용할 수 있음

[options="header"]
|===
|람다|메서드 레퍼런스 단축 표현
|`(Apple a) -> a.getWeight()`|`Apple::getWeight`
|`(Integer a) -> a.parseInt()`|`Integer::parseInt`
|`() -> Thread.currnetThread().dumpStack()`|`Thread.currentThread()::dumpStack`
|`(str, i) -> str.substring(i)`|`String::substring`
|`(String s) -> System.out.println(s)`|`System.out::println`
|===

===== 메서드 레퍼런스를 만드는 방법
* 메서드 레퍼런스는 3가지 유형으로 구분할 수 있음

* 정적 메서드레퍼런스
** 람다 : (args) -> ClassName.staticMethod(args) +
메서드 레퍼런스 : ClassName::staticMethod
** 예를 들어 Integer의 parseInt 메서드는 Integer::parseInt로 표현할 수 있음
* 인스턴스 메서드 레퍼런스
** 람다 : (arg0, rest) -> arg0.instanceMethod(rest) +
메서드 레퍼런스 : ClassName::instanceMethod
* 예를 들어 String의 length 메서드는 String::length로 표현할 수 있음
* 기존 객체의 인스턴스 메서드 레퍼런스
** 람다 : (args) -> expr.instanceMethod(args) +
메서드 레퍼런스 : expr::instanceMethod
** 예를 들어 Transaction 객체를 할당받은 expensiveTransaction 지역변수가 있고, Transaction 객체에는 getValue가 있다면, 이를 expensiveTransaction::getValue라고 표현할 수 있음
* 생성자도 메서드 레퍼런스를 사용하여 호출할 수 있음

[source,java]
----
// 빈생성자 사용
Supplier<Apple> a = new Supplier<Apple>() {
    @Override
    public Apple get() {
        return new Apple();
    }
};
Supplier<Apple> b = () -> new Apple();
Supplier<Apple> c = Apple::new;
----

=== 참고
* http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9788968481796&orderClick=LAH&Kc=[자바 8 인 액션]